# Generated by Django 4.2.4 on 2023-08-31 18:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icq_new', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='last_message',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
