# Generated by Django 4.2.4 on 2023-10-29 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('icq_new', '0005_alter_message_chat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='last_message',
        ),
    ]
